# https://github.com/etiennedub/pyk4a/blob/master/pyk4a/config.py -> for more detailsq
FPS: 1
#    FPS_5 = 0
#    FPS_15 = 1
#    FPS_30 = 2
ImageFormat: 3
#    COLOR_MJPG = 0
#    COLOR_NV12 = 1
#    COLOR_YUY2 = 2
#    COLOR_BGRA32 = 3
#    DEPTH16 = 4
#    IR16 = 5
#    CUSTOM8 = 6
#    CUSTOM16 = 7
#    CUSTOM = 8
DepthMode: 2
#    OFF = 0
#    NFOV_2X2BINNED = 1
#    NFOV_UNBINNED = 2
#    WFOV_2X2BINNED = 3
#    WFOV_UNBINNED = 4
#    PASSIVE_IR = 5
ColorResolution: 6
#    OFF = 0
#    RES_720P = 1
#    RES_1080P = 2
#    RES_1440P = 3
#    RES_1536P = 4
#    RES_2160P = 5
#    RES_3072P = 6

ColorControlCommand: 0
#  EXPOSURE_TIME_ABSOLUTE = 0
#  AUTO_EXPOSURE_PRIORITY = 1  # deprecated
#  BRIGHTNESS = 2
#  CONTRAST = 3
#  SATURATION = 4
#  SHARPNESS = 5
#  WHITEBALANCE = 6
#  BACKLIGHT_COMPENSATION = 7
#  GAIN = 8
#  POWERLINE_FREQUENCY = 9
# k4a_wired_sync_mode_t

class WiredSyncMode(IntEnum): 1
#STANDALONE = 0
#MASTER = 1
#SUBORDINATE = 2

ColorControlMode: 0
#  AUTO = 0
#  MANUAL = 1
SynchronizedImagesOnly: True
#  True
#  False